[Service]
Host = "localhost"
Port = 49982
ConnectRetries = 3
Labels = []
OpenMsg = "device mqtt started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./device-mqtt.log"

[Writable]
LogLevel = "INFO"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

# Pre-define Devices
[[DeviceList]]
  Name = "testMqttDevice"
  Profile = "MQTT-POS-2"
  Description = "MQTT device for POS"
  Labels = [ "MQTT", "POS"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "0.0.0.0"
       Port = "1883"
       ClientId = "CommandPublisher"
       User = ""
       Password = ""
       Topic = "NoUsed"

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# Driver configs
[Driver]
IncomingSchema = "tcp"
IncomingHost = "0.0.0.0"
IncomingPort = "1883"
IncomingUser = "admin"
IncomingPassword = "public"
IncomingQos = "0"
IncomingKeepAlive = "3600"
IncomingClientId = "IncomingDataSubscriber"
IncomingTopics = "IncomingTopic1:testcommand:testMqttDevice,IncomingTopic2:testcommand:testMqttDevice"
ResponseSchema = "tcp"
ResponseHost = "0.0.0.0"
ResponsePort = "1883"
ResponseUser = "admin"
ResponsePassword = "public"
ResponseQos = "0"
ResponseKeepAlive = "3600"
ResponseClientId = "CommandResponseSubscriber"
ResponseTopic = "ResponseTopic"
