[Service]
Host = "device-mqtt"
Port = 49982
ConnectRetries = 3
Labels = []
OpenMsg = "device mqtt started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./device-mqtt.log"

[Writable]
LogLevel = "INFO"

[Clients]
  [Clients.Data]
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

# Pre-define Devices
[[DeviceList]]
  Name = "device-cv-mqtt"
  Profile = "MQTT-Device"
  Description = "MQTT device"
  Labels = ["MQTT"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "mqtt"
       Port = "1883"
       ClientId = "CommandPublisher"
       User = ""
       Password = ""
       Topic = "NoUsed"	
[[DeviceList]]
  Name = "IntelAcePoint"
  Profile = "MQTT-Device"
  Description = "MQTT device"
  Labels = ["MQTT"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "mqtt"
       Port = "1883"
       ClientId = "CommandPublisher"
       User = ""
       Password = ""
       Topic = "NoUsed"

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

# Driver configs
[Driver]
IncomingSchema = "tcp"
IncomingHost = "mqtt"
IncomingPort = "1883"
IncomingUser = ""
IncomingPassword = ""
IncomingQos = "0"
IncomingKeepAlive = "60"
IncomingClientId = "IncomingDataSubscriber"
IncomingTopics = "rfid/gw/events:EventsJSON:IntelAcePoint,enter_event:EnterEvent:device-cv-mqtt,exit_event:ExitEvent:device-cv-mqtt"
ResponseSchema = "tcp"
ResponseHost = "mqtt"
ResponsePort = "1883"
ResponseUser = ""
ResponsePassword = ""
ResponseQos = "0"
ResponseKeepAlive = "60"
ResponseClientId = "CommandResponseSubscriber"
ResponseTopic = "ResponseTopic"
AdditionalPayloadJsonValues = "lane_id:123"